spring:
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 15 min
    refreshTokenExpiration: 604800 # 7 Days
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5432/store_api
    username: postgres
    password: admin
  jpa:
    show-sql: true
stripe:
  secret: ${STRIPE_SECRET}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET}
websiteUrl: http://localhost:8080