spring:
  application:
    name: store
  jpa:
    hibernate:
      ddl-auto: update
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 15 min
    refreshTokenExpiration: 604800 # 7 Days
  profiles:
    active: dev
stripe:
  secret: ${STRIPE_SECRET}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET}